create or replace FUNCTION F_VALIDA_NIT(P_NIT VARCHAR2) RETURN VARCHAR2 AS 
V_RESULT VARCHAR2(20);
V_SUMA NUMBER;
V_CONTADOR NUMBER;
V_RESIDUO NUMBER;
V_TOTAL NUMBER;
V_GUION NUMBER;
BEGIN
  V_RESULT := 'N';
  V_CONTADOR := 2;
  V_SUMA := 0;
  V_RESIDUO := 0;
  V_GUION := INSTR(P_NIT,'-');
  --V_GUION := LENGTH(P_NIT) - 1;
  FOR I IN REVERSE 1..(V_GUION-1)
  --FOR I IN REVERSE 1..(V_GUION)
  LOOP
     V_SUMA := V_SUMA + V_CONTADOR*TO_NUMBER(SUBSTR(P_NIT,I,1));
     V_CONTADOR := V_CONTADOR + 1;
  END LOOP;
  --V_RESIDUO := V_SUMA MOD 11;
  V_TOTAL := (11 - (V_SUMA MOD 11)) MOD 11;
  IF (SUBSTR(P_NIT,V_GUION+1,1) = 'K' AND V_TOTAL = 10) THEN
    V_RESULT := 'S';
  ELSIF (SUBSTR(P_NIT,V_GUION+1,1) <> 'K') THEN
    IF (TO_NUMBER(SUBSTR(P_NIT,V_GUION+1,1)) = V_TOTAL) THEN
      V_RESULT := 'S';
    END IF;
  END IF;
  RETURN V_RESULT;
END F_VALIDA_NIT;